// Generated by CoffeeScript 1.6.3
(function() {
  var exports, impl;

  impl = require('./client-dom');

  exports = module.exports = Object.create(impl);

  exports.text = function(text) {
    return new impl.TextNode(text);
  };

  exports.el = function(tagName) {
    return new impl.Element(tagName);
  };

}).call(this);
